[package]
name = "rscsg"
version = "0.2.1"
authors = ["Martin Sandgren <carlmartus@gmail.com>"]

[dependencies]
bitflags = "1.0"

[[example]]
name = "gl"
path = "examples/gl.rs"

[dev-dependencies]
glfw = "0.41.0"
lingo = { git = "https://github.com/carlmartus/lingo", rev = "bab5d733d" }
